version: "3"
services:
  backend:
    build: back/.
    ports:
      - "8080:8080"
    networks:
      - mynetwork
  frontend:
    build: front/.
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    networks:
      - mynetwork
networks:
  mynetwork:
