name: scrapper GA

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-gcr:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: hbi-scrapper
      GAR_URL: europe-west1-docker.pkg.dev/hbi-scrapper/images
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Build docker images
        run: docker-compose up -d

      - name: Configure docker client
        run: |-
          gcloud auth configure-docker \
          europe-west1-docker.pkg.dev --quiet

      - name: Push Docker Back Image to Artifact Registry
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag python_scraper_backend:latest europe-west1-docker.pkg.dev/$PROJECT_ID/images:python_scraper_backend_latest
          docker tag python_scraper_backend:latest europe-west1-docker.pkg.dev/$PROJECT_ID/images:python_scraper_backend_$GIT_TAG
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/images/python_scraper_backend:latest
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/images/python_scraper_backend:$GIT_TAG

      - name: Push Docker front Image to Artifact Registry
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag python_scraper_frontend:latest $GAR_URL:v1.0.0.0-$(date +%s)
          docker push $GAR_URL:v1.0.0.0-$(date +%s)

#scrapper@hbi-scrapper.iam.gserviceaccount.com