name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Google Cloud Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCLOUD_REGISTRY_KEY }}

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./back
          push: true
          tags: gcr.io/hbi-scrapper/backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./front
          push: true
          tags: gcr.io/hbi-scrapper/frontend:latest