name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      PROJECT_ID: myhbi-312109
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Google Cloud Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCLOUD_REGISTRY_KEY }}

      - name: Build docker images
        run: |- 
          docker build -f ./back/Dockerfile -t scrappy_back:v1.0.0 .
          docker build -f ./front/Dockerfile  -t scrappy_front:v1.0.0 .

      - name: Configure docker client
        run: |-
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Push Docker Back Image to Artifact Registry
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag $IMAGE_NAME:v1.0.0 europe-west1-docker.pkg.dev/$PROJECT_ID/images/scrappy_back:v1.0.0
          docker tag $IMAGE_NAME:v1.0.0 europe-west1-docker.pkg.dev/$PROJECT_ID/images/scrappy_back:$GIT_TAG
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/images/scrappy_back:v1.0.0
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/images/scrappy_back:$GIT_TAG

      - name: Push Docker front1 Image to Artifact Registry
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag $IMAGE_NAME:v1.0.0 europe-west1-docker.pkg.dev/$PROJECT_ID/images/scrappy_front:v1.0.0
          docker tag $IMAGE_NAME:v1.0.0 europe-west1-docker.pkg.dev/$PROJECT_ID/images/scrappy_front:$GIT_TAG
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/images/scrappy_front:v1.0.0
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/images/scrappy_front:$GIT_TAG