name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      PROJECT_ID: hbi-scrapper
      IMAGE_NAME: scrapper
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Google Cloud Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCLOUD_REGISTRY_KEY }}

      - name: Build docker images
        run: docker-compose up -d

      - name: Configure docker client
        run: |-
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Push Docker Back Image to Artifact Registry
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag python_scraper_backend europe-west1-docker.pkg.dev/$PROJECT_ID/sneaker-lab/$IMAGE_NAME-back:$GIT_TAG
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/sneaker-lab/$IMAGE_NAME-back:$GIT_TAG

      - name: Push Docker front Image to Artifact Registry
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag python_scraper_frontend:latest europe-west1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME-front:v1.0.0-$(date +%s)
          docker tag python_scraper_frontend:latest europe-west1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME-front:$GIT_TAG
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME-front:v1.0.0-$(date +%s)
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME-front:$GIT_TAG